name: quizzler
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"  # Updated the Dart SDK version to 2.12.0 or higher.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  rflutter_alert: ^2.0.7  # Added the rFlutter Alert package as a dependency.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true